const router = require('express').Router();

const tasks = require('./tasks/routes');
const persona = require('./persona/routes');
const asesor = require('./asesor/routes');
const asignarhorarioestudiante = require('./asignar_horario_estudiante/routes');
const asistencia = require('./asistencia/routes');
const citastelemarketing = require('./citas_telemarketing/routes');
const ciudad = require('./ciudad/routes');
const contrato = require('./contrato/routes');
const control_calidad = require('./control_calidad/routes');
const datos_academicos = require('./datos_academicos/routes');
const datos_tomatis = require('./datos_tomatis/routes');
const director = require('./director/routes');
const director_general = require('./director_general/routes');
const docente = require('./docente/routes');
const empresa = require('./empresa/routes');
const entrega_libro = require('./entrega_libro/routes');
const entrevista_inicial = require('./entrevista_inicial/routes');
const estudiante = require('./estudiante/routes');
const evaluacion = require('./evaluacion/routes');
const facturar = require('./facturar/routes');
const horario = require('./horario/routes');
const marca = require('./marca/routes');
const marketing = require('./marketing/routes');
const peeacharlotte = require('./peea_charlotte/routes');
const peeailvem = require('./peea_ilvem/routes');
const peeatomatis = require('./peea_tomatis/routes');
const peeauk = require('./peea_uk/routes');
const plataformacharlotte = require('./plataforma_charlotte/routes');
const programa = require('./programa/routes');
const registrollamada = require('./registro_llamada/routes');
const representante = require('./representante/routes');
const sucursal = require('./sucursal/routes');
const telemarketing = require('./telemarketing/routes');
const tipoplataforma = require('./tipo_plataforma/routes');
const vigencia = require('./vigencia/routes');

router.use('/tasks',tasks);
router.use('/persona', persona);
router.use('/asesor',asesor);
router.use('/asignarhorarioestudiante',asignarhorarioestudiante);
router.use('/asistencia',asistencia);
router.use('/citastelemarketing',citastelemarketing);
router.use('/ciudad',ciudad);
router.use('/contrato',contrato);
router.use('/control_calidad',control_calidad);
router.use('/datos_academicos',datos_academicos);
router.use('/datos_tomatis',datos_tomatis);
router.use('/director',director);
router.use('/director_general',director_general);
router.use('/docente',docente);
router.use('/empresa',empresa);
router.use('/entrega_libro',entrega_libro);
router.use('/entrevista_inicial',entrevista_inicial);
router.use('/estudiante',estudiante);
router.use('/evaluacion',evaluacion);
router.use('/facturar',facturar);
router.use('/horario',horario);
router.use('/marca',marca);
router.use('/marketing',marketing);
router.use('/peeacharlotte',peeacharlotte);
router.use('/peeailvem',peeailvem);
router.use('/peeatomatis',peeatomatis);
router.use('/peeauk',peeauk);
router.use('/plataformacharlotte',plataformacharlotte);
router.use('/programa',programa);
router.use('/registrollamada',registrollamada);
router.use('/representante',representante);
router.use('/sucursal',sucursal);
router.use('/telemarketing',telemarketing);
router.use('/tipoplataforma',tipoplataforma);
router.use('/vigencia',vigencia);


module.exports = router; 
